apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: thuanntd2001/api:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: root-username
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret
              key: root-password
        - name: DB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: csdl-configmap
              key: database_url
        - name: API_SERVER
          valueFrom: 
            configMapKeyRef:
              name: csdl-configmap
              key: api_url
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
#  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
#      nodePort: 30000
